// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestSqlInjectionEntityFramework.Data;

#nullable disable

namespace TestSqlInjectionEntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240731142852_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TestSqlInjectionEntityFramework.Entities.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<int>("TemperatureF")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c4cd89d-f9d1-4529-baee-2fe26b5fcdac"),
                            Date = new DateOnly(2024, 7, 31),
                            Summary = "Scorching",
                            TemperatureC = 20,
                            TemperatureF = 67
                        },
                        new
                        {
                            Id = new Guid("f7007c99-f93f-4c06-b3c9-c5026a95a0f2"),
                            Date = new DateOnly(2024, 8, 1),
                            Summary = "Freezing",
                            TemperatureC = 25,
                            TemperatureF = 76
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
